site_name: Cat538's Blog

theme:
  name: material
  language: en
  favicon: images/favicon.ico
  palette:  # Offering a light and dark color palette
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.indexes
    # - navigation.expand
    # - navigation.tabs

use_directory_urls: false

nav:
  - Prologue: "index.md"
  - Exercise: "plan.md"
  - Cpp:
    - toolchain:          "cpp/toolchain.md"
    - move:               "cpp/move.md"
    - align:              "cpp/align.md"
    - ranges:             "cpp/ranges.md"
    - benchmark:          "cpp/benchmark.md"
  - Rust: 
    - rust-toolchain:     "rust/rust-toolchain.md"
    - rust-study:         "rust/rust-study.md"
    - rust-attributes:     "rust/rust-attributes.md"
    - rust-modules:       "rust/rust-modules.md"
    - rust-macro:         "rust/rust-macro.md"
    # - rust-smart pointer: "rust/rust-smart pointer.md"
    - rust-network:       "rust/rust-network.md"
    - rust-optin:         "rust/rust-option.md"
    - rust-str:           "rust/rust-str.md"
  - Tools:
    # - anaconda:           "tools/anaconda.md"
    - cmake:              "tools/cmake.md"
    - docker:             "tools/docker.md"
    - git:                "tools/git.md"
    # - matplotlib:         "tools/matplotlib.md"
    - powershell:         "tools/powershell.md"
    - profile:            "tools/profile.md"
    - regex:              "tools/regex.md"
    - mkdocs:             "tools/mkdocs.md"
  - Courses:
    - 密码分析学:           "courses/密码分析学复习.md"
    - 密码学引论:           "courses/密码学引论复习.md"
    # - 操作系统:             "courses/操作系统复习.md"
    - 算法设计与分析:        "courses/algorithm.md"
    - 编译原理:             "courses/编译原理.md"
  - Crypto:
    - ecdsa-pk-recovery:  "crypto/ecdsa-pk-recovery.md"
    - algo-rsa:           "crypto/algo-rsa.md"
    - algo-fft&ntt:       "crypto/algo-fft&ntt.md"
    - algo-montgomery:    "crypto/algo-montgomery.md"
    # - seal-ckks:          "crypto/seal-ckks.md"
  - Mlc:
    - dlc-survey:         "mlc/dlc-survey.md"
    - tvm-install:        "mlc/tvm-install.md"
    - tvm-ffi:            "mlc/tvm-ffi.md"
    - tvm-type:           "mlc/tvm-type.md"
    # - tvm-relay:          "mlc/tvm-relayIR.md"
    # - tvm-relax:          "mlc/tvm-relaxIR.md"
    - tvm-tensorIR:       "mlc/tvm-tensorIR.md"
    - tvm-lowering:       "mlc/tvm-lowering.md"
    - mlir:               "mlc/mlir.md"
    - paper-torch.fx:     "mlc/paper-torch.fx.md"
    - paper-nimble:       "mlc/paper-nimble.md"
    - paper-cortex:       "mlc/paper-cortex.md"
    - paper-dietcode:     "mlc/paper-dietcode.md"
  - About: "about.md"


markdown_extensions:
  - attr_list   # allow to add HTML attributes and CSS classes to Markdown elements
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
