site_name: Cat538's Blog

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    # - navigation.tabs.sticky

nav:
  - 前言: "index.md"
  - Rust:
    - Cargo换源: "rust/Rust换源.md"
  - Crypto:
    - ECDSA-pk-recovery: "crypto/ecdsa-pk-recovery.md"
  - 后记: "post.md"

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js